#pragma once

#include "scripting/host_config.hpp"

#include <functional>
#include <map>
#include <memory>
#include <span>
#include <string>
#include <string_view>
#include <vector>

struct lua_State;

namespace ets {

// Services outlive all native instances in this VM.
struct LuauLibraryServices {
    std::shared_ptr<const LuauHostConfig> config;
    bool host_calls {false};
};

class LuauNativeLibrary {
  public:
    virtual ~LuauNativeLibrary() = default;
    // Push exactly one exports table. Called under a protected Lua call.
    virtual void open(lua_State* state) = 0;
    virtual void cancel() noexcept {}
    virtual std::size_t pending() const { return 0; }
    virtual std::string diagnostic(std::string_view) const { return {}; }
};

struct LuauLibraryDefinition {
    std::string name;
    std::string source;
    std::vector<std::string> dependencies;
    std::function<std::unique_ptr<LuauNativeLibrary>(LuauLibraryServices&)>
        create;
    // Library-private source files, relative to the entry directory.
    std::map<std::string, std::string> modules;
};

// Generated by entisium.luau_library. Both compiler and runtime use this
// catalog.
std::span<const LuauLibraryDefinition> default_luau_libraries();
bool is_luau_library(std::string_view name);

// Owns references and instances; close() must precede lua_close(), while the
// instances themselves must outlive lua_close() (userdata finalizers).
class LuauLibraries {
  public:
    LuauLibraries(
        lua_State* root,
        LuauLibraryServices services,
        std::span<const LuauLibraryDefinition> definitions =
            default_luau_libraries()
    );
    ~LuauLibraries();
    LuauLibraries(const LuauLibraries&) = delete;
    LuauLibraries& operator=(const LuauLibraries&) = delete;
    bool contains(std::string_view name) const;
    // Push the module exports, or throw std::runtime_error. Internal modules
    // are accessible only from their owner or a declared library dependency.
    void require(lua_State* state, std::string_view name);
    void enable_host_calls();
    void cancel() noexcept;
    void close() noexcept;
    std::size_t pending() const;
    std::string diagnostic(std::string_view name, std::string_view key) const;

  private:
    struct Impl;
    std::unique_ptr<Impl> m_impl;
};

} // namespace ets
