target("entisium-http")
    set_kind("static")
    add_files("src/*.cpp")
    add_headerfiles("include/**.hpp")
    add_includedirs("include", {public = true})
    add_deps("entisium-base")
    add_packages("libcurl")

target("entisium-http-tests")
    set_kind("binary")
    set_default(false)
    add_rules("entisium.test")
    add_files("tests/*.cpp")
    add_deps("entisium-http")
    add_packages("cpp-httplib")
    add_defines("ETS_HTTP_FIXTURES=\"" .. path.join(os.projectdir(), "engine/http/tests/fixtures"):gsub("\\", "/") .. "\"")
