rule("entisium.luau.files")
    set_extensions(".luau")
    on_build_file(function() end)
rule_end()

rule("entisium.luau_library")
    add_deps("entisium.luau.files")
    on_load(function(target)
        import("luau_libraries.rules", {rootdir = path.join(os.projectdir(), "tools")}).configure_library(target)
    end)
    before_build(function(target)
        import("luau_libraries.rules", {rootdir = path.join(os.projectdir(), "tools")}).generate_library(target)
    end)
rule_end()

rule("entisium.luau.catalog")
    on_config(function(target)
        import("luau_libraries.rules", {rootdir = path.join(os.projectdir(), "tools")}).configure_catalog(target)
    end)
    before_build(function(target)
        import("luau_libraries.rules", {rootdir = path.join(os.projectdir(), "tools")}).generate_catalog(target)
    end)
rule_end()
