target("entisium-luau-playtest-scheduler")
    set_kind("static")
    add_rules("entisium.luau_library")
    set_values("luau.name", "@playtest/scheduler")
    add_files("scheduler.luau")
    add_deps("entisium-luau-task", "entisium-luau-http")

target("entisium-luau-playtest-game")
    set_kind("static")
    add_rules("entisium.luau_library")
    set_values("luau.name", "@playtest/game")
    add_files("game.luau")
    add_deps("entisium-luau-task", "entisium-luau-context-bridge", "entisium-luau-playtest-scheduler")

target("entisium-luau-playtest-context")
    set_kind("static")
    add_rules("entisium.luau_library")
    set_values("luau.name", "@context")
    add_files("context.luau")
    add_deps("entisium-luau-context-core", "entisium-luau-context-bridge", "entisium-luau-playtest-scheduler")

target("entisium-luau-playtest")
    set_kind("phony")
    add_deps("entisium-luau-playtest-game", "entisium-luau-playtest-context")
